language: node_js
dist: trusty
before_script:
  - npm install
  - npm run serve &  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
node_js: lts/*
addons:
  sauce_connect: true
script:
  - npm run test